// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltjckklugztskmdciqxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0amNra2x1Z3p0c2ttZGNpcXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNTgyNTAsImV4cCI6MjA2NDYzNDI1MH0.lCaT04j03u6TFF3bWfN_aLNi7uOP8PB7o9oUwWcEwJM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);